name: SDKHttpCore

targets:
  SDKHttpCore:
    type: framework
    platform: iOS

    sources: Sources/SDKHttpCore/Lib

    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.sdk.http.core
